version: '3.9'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: ride_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ride_app
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
